model_params:
  num_inputs: 3
  model: "UNet_Multiclass"
  feature_sizes: [64, 128, 256, 512]

data_params:
  data_path: "/data/Datastore/Cityscapes"
  batch_size: 32
  num_workers: 16
  data_type: "CityScapes"


optimiser_params:
  lr: 1.0e-3
  weight_decay: 0
  start_factor: 1.0
  end_factor: 0.1
  total_iters: 1000

trainer_params:
  gpus: [0]
  max_epochs: 2000

logging_params:
  save_dir: "./logs/"
